use tsama;

DROP TABLE IF EXISTS t_activity_log;
CREATE TABLE IF NOT EXISTS t_activity_log (
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`DATE_CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`REMOTE_ADDR` VARCHAR(40),
	`REQUEST_METHOD` VARCHAR(8),
	`REQUEST_TIME` TEXT,
	`QUERY_STRING` TEXT, 
	`HTTP_USER_AGENT` TEXT, 
	`ROUTE` VARCHAR(255)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS t_country;
CREATE TABLE IF NOT EXISTS t_country (
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`NAME` VARCHAR(255),
	`ALPHA2` VARCHAR(2),
	`ALPHA3` VARCHAR(3),
	`COUNTRYCODE` INT DEFAULT 0,
	`ISO3166_2` VARCHAR(14),
	`REGION`  VARCHAR(10),
	`SUB_REGION` VARCHAR(40),
	`INTERMEDIATE_REGION` VARCHAR(20),
	`REGION_CODE` INT DEFAULT 0,
	`SUB_REGION_CODE` INT DEFAULT 0,
	`INTERMEDIATE_REGION_CODE` INT DEFAULT 0
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS t_anon_device;
CREATE TABLE IF NOT EXISTS t_anon_device (
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`DATE_CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`REMOTE_ADDR` VARCHAR(15),
	`TOKEN` TEXT,
	`INTENT` TEXT,
	`IDENTIFIER` TEXT,
	`FOOTPRINT` TEXT,
	`USED` BOOLEAN DEFAULT 0,
	`DATE_MODIFIED` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`DATE_EXPIRE` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS t_anon_device_history;
CREATE TABLE IF NOT EXISTS t_anon_device_history (
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`DATE_CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`REMOTE_ADDR` VARCHAR(15),
	`TOKEN` TEXT,
	`IDENTIFIER` TEXT,
	`FOOTPRINT` TEXT,
	`DATE_MODIFIED` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`DATE_EXPIRE` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS t_anon_device_beans;
CREATE TABLE IF NOT EXISTS t_anon_device_beans (
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`DATE_CREATED` DATE,	
	`NUMBER` INT
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS t_anon_device_ticket;
CREATE TABLE IF NOT EXISTS t_anon_device_ticket (
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`FK_ANON_DEVICE_ID`  INT DEFAULT 0,
	`DATE_CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP,	
	`TOKEN` TEXT,
	`USED` BOOLEAN,
	`DATE_EXPIRE` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS t_user_device;
CREATE TABLE IF NOT EXISTS t_user_device (
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`FK_USER_ID`  INT DEFAULT 0,
	`FK_ANON_DEVICE_ID`  INT DEFAULT 0,
	`DATE_CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`REMOTE_ADDR` VARCHAR(15),
	`NAME` TEXT,
	`TOKEN` TEXT,
	`INTENT` TEXT,
	`IDENTIFIER` TEXT,
	`CODE` TEXT,
	`FOOTPRINT` TEXT, 
	`DATE_MODIFIED` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`DATE_EXPIRE` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`DATE_CONFIRM` DATETIME ON UPDATE CURRENT_TIMESTAMP,
	INDEX IDX_DEVICE_USER(`FK_USER_ID`),
	INDEX IDX_ANON_DEVICE_ID(`FK_ANON_DEVICE_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS t_user_device_history;
CREATE TABLE IF NOT EXISTS t_user_device_history (
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`FK_USER_ID`  INT DEFAULT 0,
	`DATE_CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`REMOTE_ADDR` VARCHAR(15),
	`TOKEN` TEXT,
	`CODE` TEXT,
	`FOOTPRINT` TEXT, 
	`DATE_MODIFIED` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`DATE_EXPIRE` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`DATE_CONFIRM` DATETIME ON UPDATE CURRENT_TIMESTAMP,
	INDEX IDX_DEVICE_USER(`FK_USER_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS t_user_registration;
CREATE TABLE IF NOT EXISTS t_user_registration (
	`ID` INT AUTO_INCREMENT PRIMARY KEY,
	`FK_COUNTRY_ID`  INT DEFAULT 0,
	`DATE_CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`REMOTE_ADDR` VARCHAR(15),
	`FIRSTNAME` VARCHAR(255),
	`LASTNAME` VARCHAR(255),
	`EMAIL` VARCHAR(255),
	`MSISDN` VARCHAR(255),
	`TOKEN` TEXT,
	`CODE` TEXT,
	`FOOTPRINT` TEXT, 
	`CONFIRMED` BOOLEAN,
	`DATE_EXPIRE` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`DATE_CONFIRM` DATETIME ON UPDATE CURRENT_TIMESTAMP,
	INDEX IDX_REG_COUNTRY(`FK_COUNTRY_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
